import { StaticImageData } from "next/image";
import { MentorImg1 } from "@/public";
import { MentorImg2 } from "@/public";
import { MentorImg3 } from "@/public";
import { MentorImg4 } from "@/public";

export type CardProps = {
  id: number;
  imgSrc: StaticImageData;
  name: string;
  position: string;
  timeZone: string;
  reviews?: number;
  nextAvailable?: string;
};

export const MentorCardPage: CardProps[] = [
  {
    id: 1,
    imgSrc: MentorImg1,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 2,
    imgSrc: MentorImg2,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 3,
    name: "Shade Mayowa",
    imgSrc: MentorImg3,
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 4,
    imgSrc: MentorImg4,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 5,
    imgSrc: MentorImg1,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 6,
    imgSrc: MentorImg2,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 7,
    imgSrc: MentorImg3,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 8,
    imgSrc: MentorImg4,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 9,
    imgSrc: MentorImg1,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 10,
    imgSrc: MentorImg2,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 11,
    imgSrc: MentorImg3,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 12,
    imgSrc: MentorImg4,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 13,
    imgSrc: MentorImg1,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 14,
    imgSrc: MentorImg2,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 15,
    imgSrc: MentorImg3,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 16,
    imgSrc: MentorImg4,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 17,
    imgSrc: MentorImg1,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 18,
    imgSrc: MentorImg2,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 19,
    imgSrc: MentorImg3,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 20,
    imgSrc: MentorImg4,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 21,
    imgSrc: MentorImg1,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 22,
    imgSrc: MentorImg2,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 23,
    imgSrc: MentorImg3,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
  {
    id: 24,
    imgSrc: MentorImg4,
    name: "Shade Mayowa",
    position: "CEO, Webmasters Inc",
    timeZone: "GMT + 1 (Nigeria)",
    reviews: 4.5,
    nextAvailable: "16th, March 2023",
  },
];
