#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Running checks on your code before committing' 🔍🧐

# Check Prettier standards
npm run check-format ||
(
    echo '🤢🤮🤢🤮 Its so ugly!! - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

echo '🏗️👷 checking for eslint errors' 🔍🧐

# Check ESLint Standards
npm run check-lint ||
(
        echo '😤🏀👋😤 Get that beans code out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

echo '🏗️👷 checking for typescript errors' 🔍🧐

# Check tsconfig standards
npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

npm run format

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'


echo '✅✅ Awesome work! ✅✅'
echo '🚀⛅ Run git push to upload your changes to the remote repository ⛅🚀'